baseURL = "/"
languageCode = "en-GB"
title = "Jack Gutts"
theme = "jackgutts"

[params]
  author = "Jack Gutteridge"
  color = "gray"
  twitter = "https://twitter.com/jackgutts"               # twitter.com/YOUR_TWITTER_ID
  instagram = "https://instagram.com/jackgutts"           # instagram.com/YOUR_INSTAGRAM_ID
  mastodon = "https://hachyderm.io/@jackgutts"           # e.g. 'https://mastodon.instance/@xxx'
  soundcloud = "https://soundcloud.com/jackgutts"
  email = "mailto:jack@kingbrick.co.uk"
  rss = true
  monoDarkIcon = true
  dateFormat = "2nd January 2006"
  show_reading_time = true

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  posts = "/:year/:month/:day/:slug/"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
